name: Daniel Peláez-Zapata
email: daniel.pelaez-zapata@ucdconnect.ie
twitter: https://twitter.com/langmuirvortex
github: https://github.com/dspelaez
discourse: https://wise.discourse.group/
orcid: https://orcid.org/0000-0001-5862-6194
description: >
  Physical oceanographer studying ocean surface waves and air-sea interactions

markdown: kramdown
baseurl: ""
highlightjs_theme: "zenburn"

plugins:
  - jekyll-paginate


#paginate: 3
#paginate_path: "/page:num/"
