name: Daniel Peláez-Zapata
email: daniel.pelaez-zapata@ucdconnect.ie
twitter: https://twitter.com/dnlsntg09
github: https://github.com/dspelaez
description: >
  Physical oceanographer studying ocean surface waves and air-sea interactions

markdown: kramdown
baseurl: ""
highlightjs_theme: "zenburn"

plugins:
  - jekyll-paginate


#paginate: 3
#paginate_path: "/page:num/"
